### PR TITLE
[[FIX]] Wrong utterances generated (endPos = 0 < startPos)

### LINKED ISSUE #2: Wrong utterances generated (endPos = 0 < startPos)
Utterances such as:

```yaml
- "[${my.entity}:my.entity] ${my_list}"
```

Generates the following invalid JSON:

```json
    {
      "text": "impuestos details",
      "intent": "tef.intent.bill.check",
      "entities": [
        {
          "entity": "tef.billconcept",
          "startPos": 1,
          "endPos": 0
        }
      ]
    }
```

### PR DESCRIPTION
**Pull request by palmerabollo**
Fixes #2

### CODE REVIEW

File: src/parser.ts [hunk 1]
```diff
@@ -217,8 +217,12 @@ export class LanguageModelParser {
     }
 
     private tokenize(sentence: string): string[] {
+        if (sentence === '') {
```
Comment (palmerabollo) [inline src/parser.ts:220]: Fix: return empty array `[]` instead of `['']`
